# Generated by Django 2.1.7 on 2020-05-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_type',
            name='auther',
            field=models.ForeignKey(default='e628e007347043aea0afad515a45d7bd', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
