# Generated by Django 2.1.7 on 2020-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_auto_20200508_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_type',
            name='catagory',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
