# Generated by Django 2.1.7 on 2020-05-08 17:40

import blog_post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_post', '0003_auto_20200508_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_ground', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('catagory', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('blog_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Blog Title')),
                ('content', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Blog content')),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=40, verbose_name='Link Name')),
                ('image', models.ImageField(blank=True, null=True, unique_for_date=True, upload_to=blog_post.models.image_storage)),
                ('file_att', models.FileField(blank=True, null=True, upload_to=blog_post.models.file_storage)),
                ('url_author', models.URLField(verbose_name='Author url')),
                ('published', models.BooleanField(default=False, verbose_name='status')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post.Blog_type')),
            ],
        ),
    ]
