# Generated by Django 2.1.7 on 2020-05-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_background_blog_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelTable(
            name='background',
            table='Background_img',
        ),
        migrations.AlterModelTable(
            name='blog_post',
            table='Blogs',
        ),
    ]
