# Generated by Django 2.1.7 on 2020-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0006_auto_20200509_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='back_ground',
            field=models.ImageField(blank=True, null=True, upload_to='background'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
