# Generated by Django 2.1.7 on 2020-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_auto_20200509_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='url_author',
            field=models.URLField(verbose_name='Author url'),
        ),
    ]
