# Generated by Django 2.1.7 on 2020-05-09 17:25

import blog_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_auto_20200509_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_post.models.image_storage),
        ),
    ]
