# Generated by Django 2.1.7 on 2020-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0011_auto_20200511_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='url_author',
            field=models.URLField(blank=True, null=True, verbose_name='Author url'),
        ),
    ]
