# Generated by Django 2.1.7 on 2020-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0012_auto_20200511_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Link Name'),
        ),
    ]
