# Generated by Django 2.1.7 on 2020-05-07 15:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, default='Berhampur', max_length=50, null=True)),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Countrey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrey_name', models.CharField(default='india', max_length=30, verbose_name='countrey')),
            ],
            options={
                'db_table': 'countrey',
                'ordering': ['countrey_name'],
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, default='Ganjam', max_length=30, null=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, default='Odisha', max_length=30, null=True)),
                ('count', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Districts', to='User_Accounts.Countrey')),
            ],
            options={
                'db_table': 'states',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.UUID('77bcd7ff-2296-46b4-a4b1-723b9bee9955'), primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='fullname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('house_num', models.CharField(default='4/1', max_length=7, verbose_name='House Numebr/Flat Number')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('pin_code', models.CharField(default='760008', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.States'),
        ),
        migrations.AddField(
            model_name='cities',
            name='dist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.Districts'),
        ),
    ]
