# Generated by Django 2.1.7 on 2020-05-07 15:34

import User_Accounts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=User_Accounts.models.image_path, verbose_name='profile_photo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('526e7779-51f6-4be2-aa0c-f3a5f7a68ae6'), primary_key=True, serialize=False),
        ),
    ]
