# Generated by Django 2.1.7 on 2020-05-07 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0002_auto_20200507_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.Cities'),
        ),
        migrations.AddField(
            model_name='users',
            name='countrey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.Countrey'),
        ),
        migrations.AddField(
            model_name='users',
            name='dist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.Districts'),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.States'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9b22733-4e0c-4aed-b16f-b83fcb07902e'), primary_key=True, serialize=False),
        ),
    ]
