# Generated by Django 2.1.7 on 2020-05-07 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0003_auto_20200507_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa72c57f-b52c-40ff-82e8-73865bb34d00'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='profile_photo'),
        ),
    ]
