# Generated by Django 2.1.7 on 2020-05-08 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0005_auto_20200508_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10f9af79-12e5-477b-ad59-49392322355c'), primary_key=True, serialize=False),
        ),
    ]
