# Generated by Django 2.1.7 on 2020-05-08 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0006_auto_20200508_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd8b6181-4130-48df-a640-a4fb3952a3de'), primary_key=True, serialize=False),
        ),
    ]
